import type { PublicHotspot, Recommendation, DevelopmentProject, ImpactMetric } from '@/lib/api/types';
import { evidenceFixture, detailFixture, scoreFixture } from '@/test/evidence-fixtures';
export { scoreFixture };
export const locality = 'School entrance and the eastern access lane, Ward 42, Shivaji Nagar extension';
export const bundle = { ...evidenceFixture, geography: { ...evidenceFixture.geography, locality } };
export const hotspot = detailFixture.hotspot;
export const publicItems: PublicHotspot[] = [
  { id:'fixture-drainage',country_code:'IN',category:'drainage', public_title:'Repeated waterlogging around the school access road', public_summary:'Illustrative test record: residents describe recurring rainwater at the school entrance and difficulty reaching the eastern access lane. A site inspection is still needed.',administrative_area:{admin1:'Rajasthan',admin2:'Jaipur',locality},public_centroid:{latitude:26.91,longitude:75.78,precision:'administrative_area'},request_count:5,priority_band:'high',public_status:'under_review',updated_at:'2026-08-22T12:00:00Z',project:null,synthetic:true},
  { id:'fixture-lighting',country_code:'BR',category:'electricity', public_title:'Iluminação na passagem para a escola e o transporte público',public_summary:'Registro ilustrativo de teste: falta de iluminação na passagem entre a escola e o ponto de ônibus. Verificação do local pendente.',administrative_area:{admin1:'São Paulo',admin2:'Campinas',locality:'Passagem da Escola Municipal e acesso ao Terminal de Transporte, Jardim das Comunidades'},public_centroid:{latitude:-22.9,longitude:-47.06,precision:'administrative_area'},request_count:3,priority_band:'medium',public_status:'monitoring',updated_at:'2026-08-20T12:00:00Z',project:null,synthetic:true},
  { id:'fixture-road',country_code:'IN',category:'roads', public_title:'स्कूल और सामुदायिक स्वास्थ्य केंद्र तक पहुँचने वाले रास्ते की स्थिति',public_summary:'केवल परीक्षण रिकॉर्ड: स्थानीय रास्ते पर पानी और क्षति की रिपोर्ट। मौके की जाँच अभी बाकी है।',administrative_area:{admin1:'Rajasthan',admin2:'Jaipur',locality:'स्कूल परिसर, सामुदायिक स्वास्थ्य केंद्र और बस स्टॉप को जोड़ने वाला पूर्वी रास्ता'},public_centroid:{latitude:26.91,longitude:75.78,precision:'administrative_area'},request_count:4,priority_band:'medium',public_status:'under_review',updated_at:'2026-08-20T12:00:00Z',project:null,synthetic:true},
];
export const recommendation: Recommendation = { recommendation_id:'fixture-recommendation',hotspot_id:'hotspot-1',evidence_bundle_id:'bundle-1',title:`Inspect the drain and restore access · ${locality}`,problem:'Illustrative test record: repeated flooding affects the school entrance and the route to the bus stop.',proposed_intervention:'Inspect and clear the drain, then assess whether a repair is needed. Awaiting human review.',intended_beneficiaries:120,supporting_evidence_ids:['fixture-locality-notes','fixture-drainage-bundle'],risks:['Rainwater may have more than one source; inspection is needed.'],missing_information:['Current site inspection and drainage condition.'],confidence:.7,status:'under_review',ai_draft:true,human_approved:false,assigned_department:null,assigned_reviewer:null,created_at:'2026-08-22T12:00:00Z',updated_at:'2026-08-22T12:00:00Z',schema_version:'1'};
export const project: DevelopmentProject = {project_id:'fixture-project',recommendation_id:'fixture-approved-recommendation',hotspot_id:'fixture-hotspot',country_code:'IN',title:'Illustrative project measurement · eastern school access and drainage corridor',sector:'drainage',status:'assessment',assigned_department:null,milestones:[],created_at:'2026-08-22T12:00:00Z',updated_at:'2026-08-22T12:00:00Z',schema_version:'1'};
export const metrics: ImpactMetric[] = [{metric_id:'fixture-metric',project_id:'fixture-project',metric_code:'access_disruption_days',baseline:12,current:10,target:3,unit:'days',source_id:'fixture-measurement-record',measured_at:'2026-08-22T12:00:00Z',confidence:.6,outcome_status:'monitoring',recorded_at:'2026-08-22T12:00:00Z',schema_version:'1'}];
