import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { PublicLocaleProvider, usePublicLocale } from '@/components/providers/public-locale-provider';
import { PublicHotspotCard } from '@/components/public-hotspots/public-hotspot-card';
import { PublicDetail, PublicHotspotState } from '@/components/public-hotspots/public-hotspot-explorer';
import { EvidenceScoringView, type TabId } from '@/components/evidence/evidence-scoring-workspace';
import { Queue, Brief, DecisionRail, RecommendationDraftForm, ProjectImpactCard, Loading, State } from '@/components/csr-impact/csr-impact-shell';
import { Skeleton } from '@/components/ui/skeleton';
import { Button } from '@/components/ui/button';
import { bundle, hotspot, scoreFixture, publicItems, recommendation, project, metrics } from './fixtures';
import '@/app/globals.css';
import './preview.css';

function PreviewHeader(){const {locale,setLocale}=usePublicLocale();return <header className="sticky top-0 z-50 border-b border-border bg-background"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between px-4"><span className="font-heading text-2xl">CivicBridge</span><label className="text-sm">Language <select id="header-mobile-locale" value={locale} onChange={event=>setLocale(event.target.value as typeof locale)} className="ml-2 h-10 rounded-lg border border-border bg-card px-2"><option value="en">English</option><option value="hi">हिन्दी</option><option value="pt">Português</option></select></label></div></header>}

function Preview() {
  const {locale,t} = usePublicLocale();
  const [surface,setSurface] = useState('public');
  const [selectedId,setSelectedId] = useState<string|null>(null);
  const [tab,setTab] = useState<TabId>('overview');
  const [note,setNote] = useState(''); const [reason,setReason] = useState('');
  const [hotspotId,setHotspotId] = useState('hotspot-1'); const [bundleId,setBundleId] = useState('bundle-1'); const [title,setTitle] = useState(`drainage · ${bundle.geography.locality}`);
  const [message,setMessage] = useState(''); const [large,setLarge] = useState(false);
  const [queueCollapsed,setQueueCollapsed] = useState(false); const [drawerOpen,setDrawerOpen] = useState(false); const [draftOpen,setDraftOpen] = useState(true);
  const [selectedRecommendationId,setSelectedRecommendationId] = useState(recommendation.recommendation_id); const [mobileScreen,setMobileScreen] = useState<'queue'|'brief'>('brief');
  const policyItems=[recommendation,{...recommendation,recommendation_id:'fixture-two',title:'Review street access · missing site evidence'}];
  const selectedRecommendation=policyItems.find(item=>item.recommendation_id===selectedRecommendationId) ?? recommendation;
  const selected=publicItems.find(item=>item.id===selectedId);
  return <><style>{`html {font-size:${large?32:16}px}`}</style><div data-no-ui-translation className="fixture-banner">ISOLATED TEST FIXTURES · no live records, staff session, or API writes</div><PreviewHeader/><nav data-no-ui-translation aria-label="Fixture surfaces" className="fixture-toolbar">{['public','evidence','policy','impact','states'].map(value=><Button key={value} aria-pressed={surface===value} variant={surface===value?'default':'outline'} onClick={()=>{setSurface(value);setSelectedId(null);}}>{value}</Button>)}<Button variant="outline" aria-pressed={large} onClick={()=>setLarge(!large)}>Text size {large?'100%':'200%'}</Button></nav>
    {message && <p data-no-ui-translation role="status" className="fixture-message">{message}</p>}
    {surface==='public' && <main id="main-content" className="fixture-content"><h1 className="mb-6 font-heading text-4xl">Populated public cards · test records</h1><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{publicItems.map(item=><PublicHotspotCard key={item.id} item={item} selected={selectedId===item.id} onSelect={setSelectedId}/>)}</div>{selected && <PublicDetail item={selected} onClose={()=>setSelectedId(null)} locale={locale} t={t}/>}</main>}
    {surface==='evidence' && <EvidenceScoringView hotspotId="hotspot-1" bundle={bundle} hotspot={hotspot} activeTab={tab} onTabChange={setTab} scoreData={scoreFixture} scoreError={false} technical={true} viewLabel="Component preview"/>}
    {surface==='policy' && <main id="main-content" className="fixture-content staff-workspace"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-border pb-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-accent">Policymaker workspace · fixture</p><h1 className="font-heading text-3xl">Policy &amp; impact</h1></div><Button className="hidden lg:inline-flex" variant="outline" onClick={()=>setQueueCollapsed(!queueCollapsed)}>{queueCollapsed?'Show queue':'Hide queue'}</Button></div><nav aria-label="Mobile policy sections" className="mt-4 grid grid-cols-2 gap-1 rounded-xl bg-card p-1 lg:hidden"><button className={`min-h-11 rounded-lg text-sm font-semibold ${mobileScreen==='queue'?'bg-accent text-accent-foreground':'text-muted-foreground'}`} onClick={()=>setMobileScreen('queue')}>Queue</button><button className={`min-h-11 rounded-lg text-sm font-semibold ${mobileScreen==='brief'?'bg-accent text-accent-foreground':'text-muted-foreground'}`} onClick={()=>setMobileScreen('brief')}>Brief</button></nav>{draftOpen && <RecommendationDraftForm hotspotId={hotspotId} setHotspotId={setHotspotId} bundleId={bundleId} setBundleId={setBundleId} title={title} setTitle={setTitle} pending={false} submit={()=>setMessage('Fixture only: proposal was not created.')} cancel={()=>setDraftOpen(false)}/>}<div className={`mt-5 grid min-w-0 gap-5 ${queueCollapsed?'lg:grid-cols-[3rem_minmax(0,1fr)]':'lg:grid-cols-[minmax(17rem,21rem)_minmax(0,1fr)]'}`}><div className={mobileScreen==='queue'?'block':'hidden lg:block'}>{!queueCollapsed&&<Queue items={policyItems} selectedId={selectedRecommendationId} select={(item)=>{setSelectedRecommendationId(item.recommendation_id);setNote('');setReason('');setMobileScreen('brief');}}/>}</div><div className={mobileScreen==='brief'?'min-w-0':'hidden min-w-0 lg:block'}><div className="mb-3 flex justify-end"><Button onClick={()=>setDrawerOpen(true)}>Record decision</Button></div><Brief item={selectedRecommendation}/></div></div>{drawerOpen&&<div className="fixed inset-0 z-[70] flex justify-end bg-black/50" onMouseDown={(event)=>{if(event.target===event.currentTarget)setDrawerOpen(false);}}><section role="dialog" aria-modal="true" aria-label="Decision drawer fixture" className="h-full w-full max-w-lg overflow-y-auto bg-card p-6"><div className="flex items-center justify-between"><h2 className="font-heading text-3xl">Record decision</h2><Button variant="ghost" onClick={()=>setDrawerOpen(false)}>Close</Button></div><DecisionRail item={selectedRecommendation} note={note} setNote={setNote} reason={reason} setReason={setReason} pending={false} receipt={null} confirm={()=>setMessage('Fixture only: no decision was recorded.')} createProject={()=>setMessage('Fixture only: no project was created.')} projectPending={false}/></section></div>}</main>}
    {surface==='impact' && <main id="main-content" className="fixture-content staff-workspace"><h1 className="mb-5 text-3xl">Projects and measured impact · test records</h1><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><ProjectImpactCard project={project} metrics={metrics}/><ProjectImpactCard project={{...project,project_id:'fixture-empty',title:'Measurement pending · fixture'}} metrics={[]}/><ProjectImpactCard project={{...project,project_id:'fixture-error',title:'Unavailable measurement · fixture'}} error/></div></main>}
    {surface==='states' && <main id="main-content" className="fixture-content grid grid-cols-1 gap-5"><h1 className="text-3xl">Loading, empty and error · test states</h1><div role="status" aria-label="Loading public infrastructure updates" className="grid gap-4 md:grid-cols-2"><Skeleton className="h-64"/><Skeleton className="h-64"/></div><PublicHotspotState title={t('emptyTitle')} body={t('emptyBody')}/><PublicHotspotState title={t('unavailable')} body={t('hotspotUnavailableBody')} retry={()=>setMessage('Fixture retry only.')} retryLabel={t('retry')}/><Loading/><State icon={null} title="No recommendations in this view" message="Illustrative empty state."/><State icon={null} title="Recommendations unavailable" message="Illustrative error state." retry={()=>setMessage('Fixture retry only.')}/></main>}
  </>;
}
createRoot(document.getElementById('root')!).render(<PublicLocaleProvider><Preview/></PublicLocaleProvider>);
