export type Hotspot = {
  id: string;
  title: string;
  agency: string;
  location: string;
  sector: "Water" | "Sanitation" | "Roads" | "Drainage" | "Electricity" | "Connectivity" | "Waste" | "Infrastructure" | "Health" | "Education";
  date: string;
  urgency: "Critical" | "High" | "Moderate";
  country: "India" | "Brazil" | "South Africa";
  reports: number;
  summary: string;
};

export const homeStats = [
  { label: "Citizen reports processed", value: "142,500+" },
  { label: "Active spatial hotspots", value: "38" },
  { label: "Ranked infrastructure projects", value: "24" },
] as const;

export const howItWorks = [
  {
    step: "01",
    title: "Citizen Voice Intake",
    description:
      "Citizens submit reports in their native language (Hindi, Portuguese, English, etc.) via voice notes or text forms.",
  },
  {
    step: "02",
    title: "AI Normalization & Extraction",
    description:
      "Gemini transcribes speech, translates to working English, masks PII, and extracts structured issue records.",
  },
  {
    step: "03",
    title: "Deterministic Scoring & Ranking",
    description:
      "The scoring engine calculates explainable Need and Action scores, updating public hotspots and ranking project briefs.",
  },
] as const;

export const hotspots: Hotspot[] = [
  {
    id: "hotspot-1",
    title: "Old City Stormwater Drainage Repair",
    agency: "Municipal Infrastructure Bureau",
    location: "Jaipur Ward 1",
    sector: "Drainage",
    date: "Aug 2026",
    urgency: "Critical",
    country: "India",
    reports: 42,
    summary:
      "AI-surfaced critical hotspot for drainage blockages causing road waterlogging during monsoon.",
  },
  {
    id: "hotspot-2",
    title: "Upper Rocinha Water Pump Restoration",
    agency: "Rio Public Utilities Commission",
    location: "Rio District 2",
    sector: "Water",
    date: "Aug 2026",
    urgency: "High",
    country: "Brazil",
    reports: 31,
    summary:
      "Multiple citizen voice complaints highlighting water supply outages affecting upper slope neighborhoods.",
  },
  {
    id: "hotspot-3",
    title: "Khayelitsha Primary Road Refurbishment",
    agency: "Cape Town Works Department",
    location: "Cape Town Ward 36",
    sector: "Roads",
    date: "Aug 2026",
    urgency: "High",
    country: "South Africa",
    reports: 28,
    summary:
      "High-need hotspot generated by pothole reports along main transit corridors, backed by equity indicators.",
  },
] as const;

export const testimonials = [
  {
    quote:
      "By recording a short voice note in Hindi, my report was translated and analyzed by the central panel in minutes.",
    name: "Rajesh Sharma",
    role: "Citizen, Jaipur",
  },
  {
    quote:
      "Instead of subjective complaints, we now have a ranked pipeline of projects backed by explainable need scores.",
    name: "Dr. Ana Silva",
    role: "Government Analyst, Rio",
  },
] as const;

export const onboardingPanels = [
  {
    title: "Citizen intake portal",
    description:
      "Submit an infrastructure complaint or service outage report using text or voice recordings in your local language.",
    href: "/volunteer",
    cta: "Open intake portal",
  },
  {
    title: "CivicBridge analyst console",
    description:
      "Review AI-normalized requests, verify low-confidence extractions, and inspect prioritized demand hotspots.",
    href: "/command-center",
    cta: "Open analyst console",
  },
  {
    title: "Infrastructure impact dashboard",
    description:
      "Track approved public works projects, review AI project briefs, record decisions, and check target metrics.",
    href: "/csr-impact",
    cta: "View impact dashboard",
  },
] as const;
